language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"
  - echo DOCKER_USERNAME
  - echo DOCKER_PASSWORD

## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
script:
  - docker --version # print the version for logging
  - node -v
  - docker build -t udagram-api-feed ./udagram-api-feed
  - node -v
  - docker build -t udagram-api-user ./udagram-api-user
  - node -v
  - docker build -t udagram-frontend ./udagram-frontend
  - node -v
  - docker build -t reverseproxy ./udagram-reverseproxy
## Tagging
  - docker tag udagram-api-feed larryng95/udagram-api-feed:v1
  - docker tag udagram-api-user larryng95/udagram-api-user:v1
  - docker tag udagram-frontend larryng95/udagram-frontend:v1
  - docker tag reverseproxy larryng95/reverseproxy:v1

after_success:
  - echo DOCKER_PASSWORD | docker login -u DOCKER_USERNAME --password-stdin
  - docker push larryng95/udagram-api-feed:v1
  - docker push larryng95/udagram-api-user:v1
  - docker push larryng95/udagram-frontend:v1
  - docker push larryng95/reverseproxy:v1
