language: node_js
node_js:
  - 14

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

## Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
## Use either `docker-compose` or individual `docker build` commands
## Build
script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-feed ./udagram-api-feed .
  - docker tag udagram-api-feed larryng95/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user .
  - docker tag udagram-api-user larryng95/udagram-api-user:v1
  - docker build -t udagram-api-frontend ./udagram-api-frontend .
  - docker tag udagram-api-frontend larryng95/udagram-api-frontend:v1
  - docker build -t udagram-api-reverseproxy ./udagram-api-reverseproxy .
  - docker tag udagram-api-reverseproxy larryng95/udagram-api-reverseproxy:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push larryng95/udagram-api-feed:v1
  - docker push larryng95/udagram-api-user:v1
  - docker push larryng95/udagram-api-frontend:v1
  - docker push larryng95/udagram-api-reverseproxy:v1
