apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 80
  selector:
    service: reverseproxy
